# Generated by Django 3.1.2 on 2020-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempHumRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_logged', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(blank=True)),
                ('humidity', models.FloatField(blank=True)),
            ],
        ),
    ]
