# Generated by Django 3.1.2 on 2020-12-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temphumrecord',
            options={'verbose_name': 'Temperature Record'},
        ),
    ]
