# Generated by Django 3.1.2 on 2020-10-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201012_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(default='Plant Expert', max_length=20, verbose_name='Plant Expert'),
        ),
    ]
