# Generated by Django 3.1.2 on 2020-10-06 22:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_gnomepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='StorePage',
        ),
        migrations.DeleteModel(
            name='GnomePage',
        ),
    ]
