# Generated by Django 3.1.2 on 2020-10-13 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(blank=True, default=0, help_text="Put a really high number for 'infinite' stock", verbose_name='Inventory In Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=2, max_length=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Star Rating (0-5)'),
        ),
    ]
